inventory/webapp/urls.py
from django.urls import path, re_path
from . import views
from accounts.views import login_view, logout_view, UserRegisterView
app_name = 'webapp'
urlpatterns = [
    re_path(r'^$', views.index, name= 'index'),
    re_path(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name = 'details'),
    path('register/', UserRegisterView.as_view(), name = 'register'),
    path('login/', login_view , name = 'login'),
    path('logout/', logout_view, name = 'logout'),
    path('about/', views.about, name = 'about'),
    path('home/', views.HomeView.as_view(),name = 'home'),

    path('home/add', views.MasterInAdd.as_view(),name = 'master-add'),
    path('home/update', views.update_master, name = "master-update"),

    # /consum/add/
    path('consum/add/', views.ConsumInAdd.as_view(), name ='consum-add'),
    path('consum/', views.ConsumInView.as_view(), name ='consum'),

    path('issue/add/', views.IssueInAdd.as_view(), name ='issue-add'),
    path('issue/', views.IssueInView.as_view(), name ='issue'),

    path('whouse/add/', views.WhouseInAdd.as_view(), name ='whouse-add'),
    path('whouse/', views.WhouseInView.as_view(), name ='whouse'),
    re_path(r'^whouse/(?P<pk>[0-9]+)/$', views.WhouseInUpdate.as_view(), name ='whouse-update'),
    re_path(r'^whouse/(?P<pk>[0-9]+)/delete/$', views.WhouseInDelete.as_view(), name ='whouse-delete'),

    path('item/add/', views.ItemInAdd.as_view(), name ='item-add'),
    path('item/', views.ItemInView.as_view(), name ='item'),
    re_path(r'^item/(?P<pk>[0-9]+)/$', views.ItemInUpdate.as_view(), name ='item-update'),
    re_path(r'^item/(?P<pk>[0-9]+)/delete/$', views.ItemInDelete.as_view(), name ='item-delete'),
    # display fsn list
    path('fsn/', views.fast_moving, name = 'fsn'),
    path('reorder/', views.reorder, name = 'reorder'),
    path('abc/', views.abc_list, name = 'abc_list'),
    path('not/', views.n_list, name = 'n_list'),
    path('help/', views.help, name = 'help')
]

inventory/website/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('',include('webapp.urls')),
]

inventory/webapp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
#
from django.urls import reverse

class WhouseIn(models.Model):
    whouse_code = models.IntegerField(primary_key=True)
    whouse_name = models.CharField(max_length=20, blank=False, null=False)
    whouse_address = models.CharField(max_length=30, blank=False, null=False)
    whouse_location = models.CharField(max_length=20, blank=False, null=False)
    whouse_city = models.CharField(max_length=10, blank=False, null=False)
    whouse_phone = models.CharField(db_column='whouse_Phone', max_length=11, blank=False, null=False)  # Field name made lowercase.
    whouse_mobile = models.CharField(max_length=11, blank=False, null=False)
    whouse_head_name = models.CharField(max_length=15, blank=False, null=False)
    whouse_pincode = models.CharField(max_length=6, blank=False, null=False)

    class Meta:
        #managed = False
        db_table = 'whouse_in'

    def __str__(self):
        return str(self.whouse_code) + '-' + self.whouse_name

    def get_absolute_url(self):
        return reverse('webapp:whouse', kwargs={})

class MasterIn(models.Model):
    item_code = models.CharField(primary_key=True, max_length=10)
    item_name = models.CharField(db_column='Item_name', max_length=15, blank=False, null=False)  # Field name made lowercase.
    item_qty = models.DecimalField(db_column='Item_qty', max_digits=15, decimal_places=2, blank=False, null=False)  # Field name made lowercase.
    item_rate = models.DecimalField(db_column='Item_rate', max_digits=15, decimal_places=2, blank=False, null=False)  # Field name made lowercase.
    item_bal_qty = models.DecimalField(db_column='Item_bal_qty', max_digits=15, decimal_places=2, blank=False, null=False)  # Field name made lowercase.
    item_new_rate = models.DecimalField(db_column='Item_new_rate', max_digits=15, decimal_places=2, blank=False, null=False)  # Field name made lowercase.
    whouse_code = models.ForeignKey('WhouseIn', models.DO_NOTHING, db_column='Whouse_code')  # Field name made lowercase.

    class Meta:
        #managed = False
        db_table = 'master_in'

    def __str__(self):
        return str(self.item_code)

    def __repr__(self):
        return str(self.item_code) + '-' + self.item_name

    def get_absolute_url(self):
        return reverse('webapp:home', kwargs={})


class ConsumIn(models.Model):
    sl_no = models.AutoField(primary_key=True)
    item_code = models.ForeignKey('MasterIn', models.DO_NOTHING, db_column='item_code', blank=False, null=False)
    date_consum = models.DateField(db_column='Date_consum', blank=False, null=False)  # Field name made lowercase.
    item_consum_qty = models.DecimalField(db_column='Item_consum_qty', max_digits=15, decimal_places=2, blank=False, null=False)  # Field name made lowercase.
    item_consum_rate = models.DecimalField(db_column='Item_consum_rate', max_digits=15, decimal_places=2, blank=False, null=False)  # Field name made lowercase.

    class Meta:
        #managed = False
        db_table = 'consum_in'

    def get_absolute_url(self):
        return reverse('webapp:consum', kwargs={})



class IssueIn(models.Model):
    sl_no = models.AutoField(primary_key=True)
    item_code = models.ForeignKey('MasterIn', models.DO_NOTHING, db_column='item_code', blank=False, null=False)
    date_issue = models.DateField(db_column='Date_issue', blank=False, null=False)  # Field name made lowercase.
    item_issue_qty = models.DecimalField(db_column='Item_issue_qty', max_digits=15, decimal_places=2, blank=False, null=False)  # Field name made lowercase.
    item_issue_rate = models.DecimalField(db_column='Item_issue_rate', max_digits=15, decimal_places=2, blank=False, null=False)  # Field name made lowercase.

    class Meta:
        #managed = False
        db_table = 'issue_in'

    def get_absolute_url(self):
        return reverse('webapp:issue', kwargs={})

class ItemIn(models.Model):
    item_code = models.ForeignKey('MasterIn', models.DO_NOTHING, db_column='item_code', primary_key=True)
    item_name = models.CharField(db_column='Item_name', max_length=15, blank=False, null=False)  # Field name made lowercase.
    item_reorder_qty = models.DecimalField(db_column='Item_reorder_qty', max_digits=15, decimal_places=2, blank=False, null=False)  # Field name made lowercase.
    item_reorder_rate = models.DecimalField(db_column='Item_reorder_rate', max_digits=15, decimal_places=2, blank=False, null=False)  # Field name made lowercase.
    item_reorder_level = models.DecimalField(db_column='Item_reorder_level', max_digits=15, decimal_places=2, blank=False, null=False)  # Field name made lowercase.
    item_vendor_name = models.CharField(db_column='Item_vendor_name', max_length=20, blank=False, null=False)  # Field name made lowercase.
    item_vendor_address = models.CharField(db_column='Item_vendor_address', max_length=30, blank=False, null=False)  # Field name made lowercase.

    class Meta:
        #managed = False
        db_table = 'item_in'

    def __str__(self):
        return str(self.item_code) + '-' + self.item_name

    def get_absolute_url(self):
        return reverse('webapp:item', kwargs={})

inventory/webapp/views.py
# modules for creating class and getting database object
from django.views import generic
from .models import MasterIn, IssueIn, ConsumIn, WhouseIn, ItemIn
# to render a template & to
from django.shortcuts import render
# to use login_required
from django.contrib.auth.decorators import login_required #for fuction view
from django.contrib.auth.mixins import LoginRequiredMixin # for class based view
# to create ,update ,delete
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# to run coustom sql queries
from django.db import connection
# Create your views here.

# about view as function
def about(request):
    return render(request, 'webapp/about.html', {'dict_content':['Credits: ','Elon Musk']})
# index page
def index(request):
    template_name = 'webapp/index.html' #which template should i use to return?
    return render(request, template_name, {})

# class based views
# home view
class HomeView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'  # what is the login_url
    redirect_field_name = '/login/'
    template_name = 'webapp/home.html' #which template should i use to return?
    #context_object_name = 'all_items' # for List it return object_list to change it to our name object use this
    def get_queryset(self):
        return MasterIn.objects.all()

class MasterInAdd(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = '/login/'
    model = MasterIn
    fields = ['item_code', 'item_name', 'item_qty', 'item_rate', 'item_bal_qty', 'item_new_rate', 'whouse_code' ]
# product detail view
class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = '/login/'
    redirect_field_name = '/login/'
    model = MasterIn
    template_name = 'webapp/details.html'


class ConsumInView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'  # what is the login_url
    redirect_field_name = '/login/'
    template_name = 'webapp/consum.html' #which template should i use to return?
    #context_object_name = 'all_items' # for List it return object_list to change it to our name object use this
    def get_queryset(self):
        return ConsumIn.objects.all()

# to create a new ConsumIn --> selling something out Inventory
class ConsumInAdd(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = '/login/'
    model = ConsumIn
    fields = ['item_code', 'date_consum', 'item_consum_qty', 'item_consum_rate' ]

class IssueInView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'  # what is the login_url
    redirect_field_name = '/login/'
    template_name = 'webapp/issue.html' #which template should i use to return?
    #context_object_name = 'all_items' # for List it return object_list to change it to our name object use this
    def get_queryset(self):
        return IssueIn.objects.all()

# to create a new IssueIn --> bringing item into Inventory
class IssueInAdd(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = '/login/'
    model = IssueIn
    fields = ['item_code', 'date_issue', 'item_issue_qty', 'item_issue_rate' ]


class WhouseInView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'  # what is the login_url
    redirect_field_name = '/login/'
    template_name = 'webapp/whouse.html' #which template should i use to return?
    #context_object_name = 'all_items' # for List it return object_list to change it to our name object use this
    def get_queryset(self):
        return WhouseIn.objects.all()

# to add whouse
class WhouseInAdd(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = '/login/'
    model = WhouseIn
    fields = ['whouse_code', 'whouse_name', 'whouse_address', 'whouse_location', 'whouse_city',
            'whouse_phone', 'whouse_mobile', 'whouse_head_name', 'whouse_pincode' ]

class WhouseInUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = '/login/'
    model = WhouseIn
    fields = ['whouse_code', 'whouse_name', 'whouse_address', 'whouse_location', 'whouse_city',
            'whouse_phone', 'whouse_mobile', 'whouse_head_name', 'whouse_pincode' ]

class WhouseInDelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = '/login/'
    model = WhouseIn
    success_url = reverse_lazy('webapp:whouse')

class ItemInView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'  # what is the login_url
    redirect_field_name = '/login/'
    template_name = 'webapp/item.html' #which template should i use to return?
    def get_queryset(self):
        return ItemIn.objects.all()

class ItemInAdd(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = '/login/'
    model = ItemIn
    fields = ['item_code', 'item_name', 'item_reorder_qty', 'item_reorder_rate', 'item_reorder_level',
            'item_vendor_name', 'item_vendor_address' ]

class ItemInUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = '/login/'
    model = ItemIn
    fields = ['item_code', 'item_name', 'item_reorder_qty', 'item_reorder_rate', 'item_reorder_level',
            'item_vendor_name', 'item_vendor_address' ]

class ItemInDelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = '/login/'
    model = ItemIn
    success_url = reverse_lazy('webapp:item')

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

@login_required(login_url='/login/')
def update_master(request):
    template_name = 'webapp/home.html' #which template should i use to return?
    context = {
        "object_list": MasterIn.objects.all()
    }
    with connection.cursor() as cursor:
        cursor.execute("DROP VIEW IF EXISTS `item_consume_list`;")
        cursor.execute("DROP VIEW IF EXISTS `item_wise_issued_list`;")
        cursor.execute("create VIEW `item_wise_issued_list` AS (select `issue_in`.`item_code` AS `item_code`,sum(`issue_in`.`Item_issue_qty`) AS `item_total_issues` \
        from `issue_in` group by `issue_in`.`item_code`);")
        cursor.execute("create VIEW `item_consume_list` AS select `consum_in`.`item_code` AS `item_code`,sum(`consum_in`.`Item_consum_qty`) AS `item_total_consum` \
        from `consum_in` group by `consum_in`.`item_code`;")
        cursor.execute("Update master_in a,item_wise_issued_list b \
        Set a.item_bal_qty = a.item_bal_qty +b.item_total_issues  Where a.item_code=b.item_code ;")
        cursor.execute("update master_in a,item_consume_list b set a.item_bal_qty=a.item_bal_qty - b.item_total_consum \
        where a.item_code=b.item_code;")
    return render(request, template_name, context)

@login_required(login_url='/login/')
def fast_moving(request):
    template_name = 'webapp/fsn.html'
    with connection.cursor() as cursor:
        cursor.execute("select `consum_in`.`item_code` AS `item_code`,sum(`consum_in`.`Item_consum_qty`) AS `total_consumption`,count(0) AS `frequency` \
        from `consum_in` group by `consum_in`.`item_code` order by count(0);")
        fsn_list = dictfetchall(cursor)
    context = {
        "object_list": fsn_list,
        "title": "FSN List"
    }
    return render(request, template_name, context)

@login_required(login_url='/login/')
def reorder(request):
    template_name = 'webapp/reorder.html'
    with connection.cursor() as cursor:
        cursor.execute("select `a`.`item_code` AS `item_code`,`a`.`Item_name` AS `item_name`,`a`.`Item_bal_qty` AS `Balance_qty`, \
        `b`.`Item_reorder_level` AS `reorder_lvl`,`b`.`Item_vendor_name` AS `vendor_name`,`b`.`Item_vendor_address` AS `Address` \
        from (`master_in` `a` join `item_in` `b`) where ((`a`.`item_code` = `b`.`item_code`) and (`a`.`Item_bal_qty` <= `b`.`Item_reorder_level`));")
        reorder_list = dictfetchall(cursor)

    context = {
        "object_list": reorder_list,
        "title": "Reorder List"
    }
    return render(request, template_name, context)

@login_required(login_url='/login/')
def abc_list(request):
    template_name = 'webapp/abc_list.html'
    with connection.cursor() as cursor:
        cursor.execute("select `master_in`.`item_code` AS `item_code`,`master_in`.`Item_name` AS `item_name`,`master_in`.`Item_bal_qty` \
        AS `item_bal_qty`,(`master_in`.`Item_bal_qty` * `master_in`.`Item_rate`) AS `item_inventory_amount` from \
        `master_in` order by (`master_in`.`Item_bal_qty` * `master_in`.`Item_rate`) desc ;")
        abc_list = dictfetchall(cursor)

    context = {
        "object_list": abc_list,
        "title": "ABC List"
    }
    return render(request, template_name, context)

@login_required(login_url='/login/')
def n_list(request):
    ''' Not moving items '''
    template_name = 'webapp/n_list.html'
    with connection.cursor() as cursor:
        cursor.execute("select `master_in`.`item_code` AS `item_code`,`master_in`.`Item_name` AS `item_name`,`master_in`.`Item_qty` \
        AS `item_qty`,`master_in`.`Item_rate` AS `item_rate`,`master_in`.`Item_bal_qty` AS `item_bal_qty`,(`master_in`.`Item_qty` * `master_in`.`Item_rate`) \
        AS `dead_stock_amt` from `master_in` where (not(`master_in`.`item_code` in (select `consum_in`.`item_code` from `consum_in`)));")
        n_list = dictfetchall(cursor)

    context = {
        "object_list": n_list,
        "title": "Not Moving item List"
    }
    return render(request, template_name, context)

@login_required(login_url='/login/', redirect_field_name='login_error.html')
def help(request):
    template_name = 'webapp/help.html'
    return render(request, template_name, {"title": "Help"})

inventory/webapp/templates/webapp/abc_list.html
{% extends "webapp/head.html" %}
{% block title %} {{ title }}{% endblock %}
{% block content %}
{% if object_list %}
    <h3> {{ title }}</h3>
    <table class="table table-striped table-bordered ">
      <thead class="table thead-inverse">
        <tr  bgcolor="black">
          <th scope="col"><span style="color:white"><i>Item Code</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Name</i></span></th>
          <th scope="col"><span style="color:white"><i>Balance Qty</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Inventory Amount</i></span></th>
        </tr>
      </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td scope="row">{{ item.item_code }}</td>
                <td scope="row">{{ item.item_name }}</td>
                <td scope="row">{{ item.item_bal_qty }}</td>
                <td scope="row">{{ item.item_inventory_amount }}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
{% else %}
    <h3>No Items <h3>
{% endif %}
{% endblock %}

inventory/webapp/templates/webapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<title>{% block title %}Teste{% endblock %}</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'webapp/css/bootstrap.min.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">

	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#f6f6f6">
	<div class="container-fluid" style="min-height:95%; ">
		<div class="row">
			  <div class="col-sm-2">
				  <br>

			  </div>
			  <div class="col-sm-10">
				  <br>
				  <center>
				  <h1><strong>Inventory Management</strong></h1>
				  </center>
			  </div>
		</div><hr>

		<div class="row">
		  <div class="col-sm-2">
		  <br>

		  <br>
		   <!-- Great, til you resize .affix will fix the side so it stays as you scroll but next one doesn't -->
			<!--<div class="well bs-sidebar affix" id="sidebar" style="background-color:#fff">-->
			<div class="well bs-sidebar" id="sidebar" style="background-color:#fff">
			  <ul class="nav nav-pills nav-stacked">
				<li><a href='/'>Home</a></li>
                <li><a href='/login/'>Login</a></li>
                <li><a href='/register/'>Register</a></li>
				<li><a href='/about/'>About Us</a></li>
			  </ul>
			</div> <!--well bs-sidebar affix-->
		  </div> <!--col-sm-2-->
		  <div class="col-sm-10">

			<div class='container-fluid'>
			<br><br>
			   {% block body %}

			   {% endblock %}
			</div>
		  </div>
		</div>
	</div>
	<footer>
		<div class="container" style='margin-left:15px'>
			<a href="#" target="blank">Contact</a> | <a href="#" target="blank">LinkedIn</a> 
            <script>
                document.write(new Date().getFullYear())
            </script>
            
        </div>
    </div>

	</footer>

</body>

</html>

inventory/webapp/templates/webapp/consum.html
{% extends "webapp/head.html" %}
{% block title %}Sold Items{% endblock %}
{% block content %}
{% if object_list %}
    <h3>Items Sold:</h3>
    <table class="table table-striped table-bordered ">
      <thead class="table thead-inverse">
        <tr  bgcolor="black">
          <th scope="col"><span style="color:white"><i>Sl No</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Code</i></span></th>
          <th scope="col"><span style="color:white"><i>Date</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Consume Qty</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Consume Rate</i></span></th>
        </tr>
      </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td scope="row">{{ item.sl_no}}</td>
                <td scope="row"><a href="{% url 'webapp:details' item.item_code %}">{{ item.item_code}}</a></td>
                <td scope="row">{{ item.date_consum}}</td>
                <td scope="row">{{ item.item_consum_qty}}</td>
                <td scope="row">{{ item.item_consum_rate}}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
{% else %}
    <h3>No Items Sold<h3>
{% endif %}
{% endblock %}

inventory/webapp/templates/webapp/fsn.html
{% extends "webapp/head.html" %}
{% block title %} {{ title }}{% endblock %}
{% block content %}
{% if object_list %}
    <h3> {{ title }}</h3>
    <table class="table table-striped table-bordered ">
      <thead class="table thead-inverse">
        <tr  bgcolor="black">
          <th scope="col"><span style="color:white"><i>Frequency</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Code</i></span></th>
          <th scope="col"><span style="color:white"><i>Total Consumtion</i></span></th>
        </tr>
      </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td scope="row">{{ item.frequency }}</td>
                <td scope="row"><a href="{% url 'webapp:details' item.item_code %}">{{ item.item_code}}</a></td>
                <td scope="row">{{ item.total_consumption }}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
{% else %}
    <h3>No Movement of items<h3>
{% endif %}
{% endblock %}

inventory/webapp/templates/webapp/index.html
{% extends 'webapp/base.html' %}
{% load staticfiles %}
{% block body %}
        <h2>Welcome!</h2>
{% endblock %}

inventory/webapp/templates/webapp/issue.html
{% extends "webapp/head.html" %}
{% block title %}Bought Items{% endblock %}
{% block content %}
{% if object_list %}
    <h3>Items Bought:</h3>
    <table class="table table-striped table-bordered ">
      <thead class="table thead-inverse">
        <tr  bgcolor="black">
          <th scope="col"><span style="color:white"><i>Sl No</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Code</i></span></th>
          <th scope="col"><span style="color:white"><i>Date</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Issue Qty</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Issue Rate</i></span></th>
        </tr>
      </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td scope="row">{{ item.sl_no}}</td>
                <td scope="row"><a href="{% url 'webapp:details' item.item_code %}">{{ item.item_code}}</a></td>
                <td scope="row">{{ item.date_issue}}</td>
                <td scope="row">{{ item.item_issue_qty}}</td>
                <td scope="row">{{ item.item_issue_rate}}</td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
{% else %}
    <h3>No Items Bought<h3>
{% endif %}
{% endblock %}

inventory/webapp/templates/webapp/item.html
{% extends "webapp/head.html" %}
{% block title %}Item Details{% endblock %}
{% block content %}
{% if object_list %}
    <h3>Item Details:</h3>
    <table class="table table-striped table-bordered ">
      <thead class="table thead-inverse">
        <tr  bgcolor="black">
          <th scope="col"><span style="color:white"><i>Item Code</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Name</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Reorder Qty</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Reorder Level</i></span></th>
          <th scope="col"><span style="color:white"><i>Item Vendor Name</i></span></th>
          <th scope="col"><span style="color:white"><i>Edit</i></span></th>
          <th scope="col"><span style="color:white"><i>Delete</i></span></th>
        </tr>
      </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td scope="row">{{ item.item_code}}</td>
                <td scope="row">{{ item.item_name}}</td>
                <td scope="row">{{ item.item_reorder_qty}}</td>
                <td scope="row">{{ item.item_reorder_level}}</td>
                <td scope="row">{{ item.item_vendor_name}}</td>
                <td scope="row"><a href="{% url 'webapp:item-update' item.item_code %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                <td scope="row"><a href="{% url 'webapp:item-delete' item.item_code %}"><span class="glyphicon glyphicon-trash"></span></a></td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
{% else %}
    <h3>NO item Details<h3>
{% endif %}
{% endblock %}

inventory/webapp/templates/webapp/whouse.html
{% extends "webapp/head.html" %}
{% block title %}Whouse{% endblock %}
{% block content %}
{% if object_list %}
    <h3>Ware house list:</h3>
    <table class="table table-striped table-bordered ">
      <thead class="table thead-inverse">
        <tr  bgcolor="black">
          <th scope="col"><span style="color:white"><i>Ware House Code</i></span></th>
          <th scope="col"><span style="color:white"><i>Ware House Name</i></span></th>
          <th scope="col"><span style="color:white"><i>Ware House Manager</i></span></th>
          <th scope="col"><span style="color:white"><i>Ware House Contact</i></span></th>
          <th scope="col"><span style="color:white"><i>Edit</i></span></th>
          <th scope="col"><span style="color:white"><i>Delete</i></span></th>
        </tr>
      </thead>
        <tbody>
            {% for item in object_list %}
            <tr>
                <td scope="row">{{ item.whouse_code}}</td>
                <td scope="row">{{ item.whouse_name}}</td>
                <td scope="row">{{ item.whouse_head_name}}</td>
                <td scope="row">{{ item.whouse_mobile}}</td>
                <td scope="row"><a href="{% url 'webapp:whouse-update' item.whouse_code %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                <td scope="row"><a href="{% url 'webapp:whouse-delete' item.whouse_code %}"><span class="glyphicon glyphicon-trash"></span></a></td>
            </tr>
            {% endfor %}

        </tbody>
    </table>
{% else %}
    <h3>No ware house registered<h3>
{% endif %}
{% endblock %}